server:
  port: 8080

spring:
  application:
    name: microservice-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          - id: monopatines_paradas
            uri: http://localhost:8081
            predicates:
              - Path=/api/
          - id: usuarios
            uri: http://localhost:8082
            predicates:
              - Path=/api/usuarios//
          - id: mantenimiento
            uri: http://localhost:8083
            predicates:
              - Path=/api/mantenimientos/**
          - id: viajes
            uri: http://localhost:8084
            predicates:
              - Path=/api/**