server:
  port: 8080

spring:
  application:
    name: microservice-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          - id: viajes
            uri: http://localhost:8084
            predicates:
              - Path=/api/**