eureka:
  client:
    register-with-eureka: true

server:
  port: 8090

spring:
  application:
    name: microservice-gateway
  cloud:
    config:
      uri: http://config-server:8888  # URL del Config Server
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          - id: monopatines
            uri: http://monopatines-paradas:8081
            predicates:
              - Path=/api/monopatines/**
          - id: paradas
            uri: http://monopatines-paradas:8081
            predicates:
              - Path=/api/paradas/**
          - id: usuarios
            uri: http://usuarios:8082
            predicates:
              - Path=/api/usuarios/**
          - id: mercadopago
            uri: http://usuarios:8082
            predicates:
              - Path=/api/mercadopago/**
          - id: mantenimiento
            uri: http://mantenimiento:8083
            predicates:
              - Path=/api/mantenimientos/**
          - id: viajes
            uri: http://viajes:8084
            predicates:
              - Path=/api/viajes/**
          - id: tarifas
            uri: http://viajes:8084
            predicates:
              - Path=/api/tarifas/**
          - id: pausas
            uri: http://viajes:8084
            predicates:
              - Path=/api/pausas/**
  data:
    mongodb:
      host: mongo-auth
      port: 27017
      database: authdb  # Reemplaza con el nombre de tu base de datos
